### ISSUE TITLE
Kleene.ERE.leadingChars doesn't contain sufficient information

### ISSUE THREAD

**Issue by safinaskar** [phadej/kleene#18]
Consider this example:
```
> Kleene.ERE.leadingChars (Kleene.char 'a' :: Kleene.ERE.ERE Char)
fromSeparators "`a"
> Kleene.ERE.leadingChars (Kleene.complement $ Kleene.char 'a' :: Kleene.ERE.ERE Char)
fromSeparators "`a"
```

As you can see, "a" and its complement give same `leadingChars`, I think this is a bug. I propose `leadingChars` to return `RSet` instead. Same probably applies to `Kleene.RE.leadingChars`.

Also, `Kleene.ERE.leadingChars` sometimes give simply wrong answers. Consider this:
```
> Kleene.ERE.leadingChars ((Kleene.complement $ Kleene.char 'a') /\ (Kleene.char 'a'))
fromSeparators "`a"
> Kleene.ERE.leadingChars (Kleene.empty :: Kleene.ERE.ERE Char)
fromSeparators ""
> Kleene.Equiv ((Kleene.complement $ Kleene.char 'a') /\ (Kleene.char 'a' :: Kleene.ERE.ERE Char)) == Kleene.Equiv Kleene.empty
True
```
Answer is both cases should be `fromSeparators ""`

**Comment by phadej** [comment]
The behavior is not wrong. `leadingChars` is (just) wrongly named as it returns a `Partition`, not an actual leading character set.

The idea is that it's enough to try a character from each part of partition to generate (an approximte) derivative tree. So in some sense it returns more information then proper leadingChars would.

I'll rename the function if some good name is proposed. leading characters otoh is quite useless. It's also expensive to computer for EREs, as it's hard to decide whether the ERE is empty due conjunction, so at best it would be similar approximaton as `leadingChars :: -> Partition` is currently.

You can compute proper leading character set by using https://hackage.haskell.org/package/kleene-0.1/docs/Kleene-Internal-Partition.html#v:intervals and `derivate` and `equivalent empty` check.

**Comment by safinaskar** [comment]
Ok, thanks for quick response

**Comment by phadej** [comment]
No worries, it was a good question.

---

See https://www.ccs.neu.edu/home/turon/re-deriv.pdf the section *4.2 Character sets*

> We could determine the derivative classes of each state before finding any derivatives,
but in general it is not possible to compute them without doing O(|Σ|) work. Instead, we
define a function C : RE → ... by structural recursion that computes an approximation
of the derivative classes

I'll amend the docs for `leadingChars` that it actually computes *an approxmation of derivative classes*. I'll wait with renaming until there is other breaking changes.
